# Generated by Django 2.2.6 on 2019-11-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191103_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='password',
            field=models.IntegerField(default=1),
        ),
    ]
