# Generated by Django 2.2.6 on 2019-11-03 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191103_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='password',
        ),
    ]
