# Generated by Django 2.2.6 on 2019-11-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191103_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag_question',
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(to='app.Tag'),
        ),
    ]
