# Generated by Django 2.2.6 on 2019-11-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20191103_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.ImageField(null=True, upload_to='static/pictures'),
        ),
    ]
