# Generated by Django 2.2.6 on 2019-11-25 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app', '0019_auto_20191105_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')])),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Author')),
            ],
        ),
        migrations.RemoveField(
            model_name='like_question',
            name='field',
        ),
        migrations.DeleteModel(
            name='Like_Answer',
        ),
        migrations.DeleteModel(
            name='Like_Question',
        ),
    ]
