# Generated by Django 2.2.6 on 2019-11-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20191125_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedislike',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
