# Generated by Django 2.2.6 on 2019-11-25 21:32

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_likedislike_object_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='likedislike',
            managers=[
                ('oblects', django.db.models.manager.Manager()),
            ],
        ),
    ]
