# Generated by Django 2.2.6 on 2019-12-05 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20191125_2132'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='likedislike',
            managers=[
            ],
        ),
    ]
