# Generated by Django 2.2.6 on 2019-12-05 05:33

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20191205_0523'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('rat', django.db.models.manager.Manager()),
            ],
        ),
    ]
