# Generated by Django 2.2.6 on 2019-12-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20191205_0533'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='static/pictures/default.jpeg', upload_to='static/pictures'),
        ),
    ]
